# Generated by Django 4.1.7 on 2023-05-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_health', '0006_disease_user_descpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_user',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_health.doctor_user'),
        ),
        migrations.AlterField(
            model_name='disease_user',
            name='precaution',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicine_user',
            name='diseasename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_health.disease_user'),
        ),
    ]
