# Generated by Django 4.1.7 on 2023-05-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_health', '0008_alter_disease_user_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease_user',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicine_user',
            name='diseasename',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='disease_User',
        ),
        migrations.DeleteModel(
            name='doctor_User',
        ),
        migrations.DeleteModel(
            name='medicine_User',
        ),
    ]
