# Generated by Django 4.1.7 on 2023-05-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_health', '0009_remove_disease_user_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseasename', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=100)),
                ('precaution', models.CharField(max_length=500)),
                ('medicinename', models.CharField(max_length=50)),
                ('descpic', models.FileField(default='anonymous.jpg', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('specializations', models.CharField(max_length=50)),
                ('doctorpic', models.FileField(default='anonymous.jpg', upload_to='media/')),
                ('contact', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=1500)),
                ('disease', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('profilepic', models.FileField(default='anonymous.jpg', upload_to='media/')),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='medicine_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=50)),
                ('medprecaution', models.CharField(max_length=100)),
                ('meddesc', models.CharField(max_length=100)),
                ('medprice', models.CharField(max_length=10)),
                ('diseasename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_health.disease_user')),
            ],
        ),
        migrations.AddField(
            model_name='disease_user',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_health.doctor_user'),
        ),
    ]
