# Generated by Django 4.1.7 on 2023-05-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_health', '0010_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_user',
            name='medpic',
            field=models.FileField(default='anonymous.jpg', upload_to='media/'),
        ),
    ]
